#!/bin/bash
	PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

	if [ "$1" = "config" ]; then
		cloud_status -l | sort | awk \
			'BEGIN{ \
				cloudcount = 0; \
				} \

			{ \
				if ($1=="") next; \
				cloudcount++; \
				clouds[cloudcount] = $1 \
				} \

			END{ \
				for (cloud=1; cloud<=cloudcount; cloud++) { \
					print "multigraph cloud_" clouds[cloud]; \
					print "graph_title Cloud Activity on " clouds[cloud]; \
					print "graph_category Cloud"; \
					print "graph_vlabel Virtual Machines"; \
					print "graph_width 800"; \
					print "graph_height 500"; \

					print "error.label Error"; \
					print "error.draw AREA"; \
					print "error.colour 000000"; \

					print "running.label Running"; \
					print "running.draw AREA"; \
					print "running.colour 008888"; \

					print "starting.label Starting"; \
					print "starting.draw AREA"; \
					print "starting.colour cccccc\n"; \

					print "heartbeat.label Cloud Scheduler Heartbeat"; \
					print "heartbeat.draw LINE3"; \
					print "heartbeat.colour ff0000\n"; \
					} \
				}'
	else
		cloud_status -m | awk \
			'BEGIN{ \
				cloudcount = 0; \
				while (("cloud_status -l | sort" | getline line)>0) { \
					split(line, words); \
					if (words[1]!="") { \
						cloudcount++; \
						clouds[cloudcount] = words[1] \
						} \
					} \

				statecount = 3; \
				states[1] = "Error"; \
				states[2] = "Running"; \
				states[3] = "Starting"; \

				switch = "Yes" \
				} \

			/couldn\047t connect/ {switch="No"}; \

			// { \
				if ($0=="" || $1=="ID" || $1=="Total") next; \
				state="error"; \
				if ($4=="Running" || $4=="ExpiredProxy" || $4=="Retiring") state="running"; \
				if ($4=="Starting") state="starting"; \
				count[$5,state]++ \
				} \

			END{ \
				for (cloud=1; cloud<=cloudcount; cloud++) { \
					print "multigraph cloud_" clouds[cloud]; \
					print "error.value " count[clouds[cloud],"error"]+0; \
					print "running.value " count[clouds[cloud],"running"]+0; \
					print "starting.value " count[clouds[cloud],"starting"]+0; \

					if (switch=="Yes") print "heartbeat.value 0.0"; \
					print "\n" \
					} \
				}'
	fi
